name: terraform init
description: terraform init
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  github_app_token:
    description: 'GitHub Access Token'
    required: true
  working_directory:
    description: working directory
    required: false
    default: ""
  providers_lock_opts:
    description: terraform providers lock options
    required: false
    default: -platform=windows_amd64 -platform=linux_amd64 -platform=darwin_amd64
  skip_push:
    description: If "true", a commit isn't pushed to the remote branch
    required: false
  use_opentofu:
    description: If "true", OpenTofu is run instead of Terraform
    required: false
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/main.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_APP_TOKEN: ${{ inputs.github_app_token }}
        ROOT_DIR: ${{ github.workspace }}
        WORKING_DIR: ${{ inputs.working_directory }}
        EVENT_NAME: ${{ github.event_name }}
        PROVIDERS_LOCK_OPTS: ${{ inputs.providers_lock_opts }}
        SKIP_PUSH: ${{ inputs.skip_push }}
        USE_OPENTOFU: ${{ inputs.use_opentofu }}
